string(RANDOM LENGTH 12 SUFFIX)
set(ROOT "${TEST_DIR}/${SUFFIX}/mod")
set(BACKUP_DIR "${TEST_DIR}/${SUFFIX}/backups")
set(SOURCE "${PROJECT_DIR}/config/SkyUINavbar.json")
file(MAKE_DIRECTORY "${ROOT}/SKSE/Plugins" "${ROOT}/Interface/NavBarForSkyUI")
set(EDITED [=[// Keep my settings and comments exactly.
{"navbarScale":1.25,/* reveal */"fadeInSeconds":0.1,"fadeMode":"menu","showButtonHints":false,"menus":[{"menu":"MagicMenu","showNavbar":false,"showInNavbar":true}]}]=])
file(WRITE "${ROOT}/SKSE/Plugins/SkyUINavbar.json" "${EDITED}")
file(WRITE "${ROOT}/SKSE/Plugins/SkyUINavbar.ui.json" "legacy settings")
file(WRITE "${ROOT}/SKSE/Plugins/SkyUINavbar.default.json" "legacy defaults")
file(WRITE "${ROOT}/Interface/NavBarForSkyUI/NavBar.swf" "obsolete")
file(WRITE "${ROOT}/Interface/NavBar.swf" "current")
file(WRITE "${ROOT}/Interface/NavBarForSkyUI/unrelated.txt" "keep")
file(WRITE "${ROOT}/SKSE/Plugins/SkyUINavbar.tutorial.json" "seen state")
include("${PROJECT_DIR}/cmake/DeployConfig.cmake")
file(READ "${CONFIG}" RESULT)
if(NOT RESULT STREQUAL EDITED)
	message(FATAL_ERROR "Deployment changed user settings/comments/order")
endif()
if(EXISTS "${ROOT}/Interface/NavBarForSkyUI/NavBar.swf" OR EXISTS "${ROOT}/SKSE/Plugins/SkyUINavbar.ui.json" OR EXISTS "${ROOT}/SKSE/Plugins/SkyUINavbar.default.json")
	message(FATAL_ERROR "Obsolete deployment artifacts remain")
endif()
if(EXISTS "${ROOT}/SKSE/Plugins/SkyUINavbar.tutorial.json" OR NOT EXISTS "${BACKUP_ROOT}/SKSE/Plugins/SkyUINavbar.tutorial.json")
	message(FATAL_ERROR "Obsolete tutorial state was not backed up and removed")
endif()
foreach(FILE IN ITEMS "Interface/NavBar.swf" "Interface/NavBarForSkyUI/unrelated.txt")
	if(NOT EXISTS "${ROOT}/${FILE}")
		message(FATAL_ERROR "Cleanup touched ${FILE}")
	endif()
endforeach()
file(READ "${BACKUP_ROOT}/Interface/NavBarForSkyUI/NavBar.swf" OLD_SWF)
if(NOT OLD_SWF STREQUAL "obsolete")
	message(FATAL_ERROR "Obsolete SWF backup missing")
endif()
include("${PROJECT_DIR}/cmake/DeployConfig.cmake")
file(READ "${CONFIG}" AGAIN)
if(NOT AGAIN STREQUAL EDITED)
	message(FATAL_ERROR "Subsequent deployment rewrote user settings")
endif()
set(ROOT "${TEST_DIR}/${SUFFIX}/fresh")
include("${PROJECT_DIR}/cmake/DeployConfig.cmake")
file(SHA256 "${SOURCE}" EXPECTED)
file(SHA256 "${CONFIG}" ACTUAL)
if(NOT ACTUAL STREQUAL EXPECTED)
	message(FATAL_ERROR "Fresh installation differs from shipped config")
endif()
